### PR TITLE
Added gpu=False argument to SpacyPreprocessor.__init__ which calls sp…

### LINKED ISSUE #1497: Add option to SpacyPreprocessor to enable GPU support
## Is your feature request related to a problem? Please describe.

I need `snorkel.preprocess.nlp.SpacyPreprocessor` to perform better. GPU support for spacy is possible, and improves performance, if you install it via something like: `pip install spacy[cuda100]`. Therefore I want a boolean `gpu=False` option added to `SpacyPreprocessor` and if it is called it runs `spacy.prefer_gpu()` before assignin a `spacy.Doc` to `self._nlp` by calling `nlp`.

## Describe the solution you'd like

```python
spacy_processor = SpacyPreprocessor(
    text_field='_Lower_Text',
    doc_field='_Doc',
    memoize=True,
    gpu=True,
)
```

This calls:

```python
        if gpu:
            spacy.prefer_gpu()
        self._nlp = spacy.load(language, disable=disable or [])
```

## Describe alternatives you've considered

I tried importing this externally and it didn't seem to help performance. I believe it needs to be called within `SpacyPreprocessor`.

## Additional context

Performance approximately doubled for my task preprocessing.

### PR DESCRIPTION
**Pull request by rjurney**
…acy.prefer_gpu() if enabled.

## Description of proposed changes

I need snorkel.preprocess.nlp.SpacyPreprocessor to perform better. GPU support for spacy is possible, and improves performance, if you install it via something like: pip install spacy[cuda100]. Therefore I want a boolean gpu=False option added to SpacyPreprocessor and if it is called it runs spacy.prefer_gpu() before assignin a spacy.Doc to self._nlp by calling nlp.

## Related issue(s)

Fixes #1497

## Test plan

The existing tests pass, without calling with the gpu option enabled. I am not sure how to test this other than manually without creating a separate gpu test file. Is this the way to go?

## Checklist

Need help on these? Just ask!

* [x] I have read the **CONTRIBUTING** document.
* [x] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.
* [ ] I have run `tox -e complex` and/or `tox -e spark` if appropriate.
* [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by henryre** [comment]
Hi @rjurney sorry for the delay on reviewing, and thanks for the add!! This looks good to me and per your suggestion on #1497, we currently leave GPU code untested. We should still be able to land despite the failed codecov check.

As a side note: have you tried using memoization for the SpacyPreprocessor? Should speed things up significantly on re-execution.

**Comment by rjurney** [comment]
@henryre My problem is a little bit different than the examples. I have about 2,000 labels atm and will increase it as I'm able. I'm working on a multi-label classification problem, and I'm trying to use the multi-task stuff expand the number of examples on infrequent tags to include them in the model with acceptable performance.

I have 2,000 keyword match LFs as my first set, one or more for each label, and my fast PC processes them at `| 100/7000 [00:37<44:29,  2.59it/s]`. Unfortunately it is single threaded. Without the `SpacyPreprocessor` things are much faster, and I should probably just go without but there are interesting LFs I can create with it. First, I'm trying `snorkel.labeling.lf.nlp_spark.SparkNLPLabelingFunction`, as in parallel on my beefy machine it should be workable. I

```python
from snorkel.preprocess.nlp import SpacyPreprocessor
from snorkel.labeling import LabelingFunction

ABSTAIN = -1


spacy_processor = SpacyPreprocessor(
    text_field='_Lower_Text',
    doc_field='_Doc',
    memoize=True,
    gpu=True,
)

def keyword_lookup(x, keywords, label):
    
    match = any(word in x._Doc.text for word in keywords)
    # print(keywords, match, label, x)
    if match:
        return label
    return ABSTAIN

def make_keyword_lf(keywords, label=ABSTAIN):
    return LabelingFunction(
        name=f"keyword_{keywords}",
        f=keyword_lookup,
        resources=dict(keywords=keywords, label=label),
        pre=[spacy_processor]
    )


# For each keyword, split on hyphen and create an LF that detects if that tag is present in the data
keyword_lfs = OrderedDict()
for label_set, index in zip(df['_Tag'].unique(), df['_Index'].unique()):
    for label in label_set.split('-'):
        keyword_lfs[label] = make_keyword_lf(label, label=index)
```

**Comment by rjurney** [comment]
@henryre Actually, are there any examples of using `snorkel.labeling.lf.nlp_spark.SparkNLPLabelingFunction`?

**Comment by rjurney** [comment]
@henryre Hold up on this. It breaks in `SparkLFApplier` because pickle can't serialize the `cupy` array. I'll have to disable it in Spark context or something.

**Comment by rjurney** [comment]
@henryre This looks good to me, I was mistaken.

**Comment by henryre** [comment]
Closing in favor of #1523

**Pull request closed without merging**
