### PR TITLE
Add GHA build

### PR DESCRIPTION
**Pull request by gliptak**
## Description of proposed changes

https://github.com/gliptak/snorkel/actions/runs/4815047808

## Related issue(s)

Fixes # (issue)

## Checklist

Need help on these? Just ask!

* [x] I have read the **CONTRIBUTING** document.
* [x] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.
* [ ] I have run `tox -e complex` and/or `tox -e spark` if appropriate.
* [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by gliptak** [comment]
@openai please review

**Comment by humzaiqbal** [comment]
Hi @gliptak thanks for this PR! Would you mind providing a bit more detail on what this PR is aiming to do and also provide a test plan? Thanks a lot!

**Comment by gliptak** [comment]
@humzaiqbal PR is first step moving build into GHA offering better GitHub integration than CircleCI

**Comment by humzaiqbal** [comment]
Hi @gliptak, thanks for the idea! For now, our team has decided to stick with CircleCI. Happy to revisit at a later date.

**Pull request closed without merging**
