### PR TITLE
Fix dependency vulnerabilites

### PR DESCRIPTION
**Pull request by MLobo1997**
## Description of proposed changes

The [security score on Snyk](https://snyk.io/advisor/python/snorkel) is very low

## Related issue(s)

Fixes # (issue)

## Checklist

Need help on these? Just ask!

* [ ] I have read the **CONTRIBUTING** document.
* [ ] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.
* [ ] I have run `tox -e complex` and/or `tox -e spark` if appropriate.
* [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by bhancock8** [comment]
Thanks for the requested dependency upgrades, @MLobo1997! We'll wait to approve until you mark this PR as no longer in draft, but then we'd be happy to merge in changes like these.

**Comment by bhancock8** [comment]
Hmm, interesting. 🤔 We'll take a look. Thanks for flagging @MLobo1997.

**Comment by MLobo1997** [comment]
That would be great, thanks @bhancock8! If you need anything let me know. I'll polish this PR once the builds are back in place.

**Comment by bhancock8** [comment]
Sounds good. I see that we intentionally migrated from Travis to Circle back in Dec 2021. Not sure where the Circle config file went though since then. @fpoms is going to take a look.

**Comment by fpoms** [comment]
@MLobo1997 Thanks for flagging this—from what I can tell, there seems to be something amiss on the CircleCI side of things. I’ve contacted them and am working toward a resolution. Will update you when I’ve heard back!

**Review by bhancock8 — APPROVED** [review]
Pretty straightforward bump of dependencies. Looks good to me!

**Pull request merged**
