### PR TITLE
Add tqdm progress bar on  label fit method

### LINKED ISSUE #1624: Show a progress bar on LabelModel.fit
## Is your feature request related to a problem? Please describe.
When fitting a `LabelModel` with hundreds of labeling functions and thousands of datapoints, it can take several minutes to complete. When calling `fit()` on my `LabelModel`, I currently have no clue how many epochs were already processed nor an estimated ETA (even if `verbose` is set to `True`). 

## Describe the solution you'd like
When calling `LabelModel().fit()`, a `tqdm` progress bar would be displayed and updated after each epoch. This would at least be shown if `verbose=True`

## Describe alternatives you've considered
`time` library and print statements

## Additional context
Snorkel version: `snorkel==0.9.6`
Run in Jupyter lab

### PR DESCRIPTION
**Pull request by anerirana**
Fixes #1624

## Description of proposed changes

Added a tqdm progress bar when `fit()` method on `LabelModel` is called. It updates after each epoch.
tqdm2

When log frequency for loss reporting is enabled, it will be formatted this way.
tqdm3

Please let me know if I should add a `progress_bar` parameter to `fit()`, similar to `apply()` method in `PandasLFApplier`

## Related issue(s)

Fixes #1624 

## Test plan
No new test has been added, as these changes do not modify the logic

## Checklist

Need help on these? Just ask!

* [x] I have read the **CONTRIBUTING** document.
* [n/a] I have updated the documentation accordingly.
* [n/a] I have added tests to cover my changes.
* [n/a] I have run `tox -e complex` and/or `tox -e spark` if appropriate.
* [x] All new and existing tests passed.

### CODE REVIEW

**Comment by anerirana** [comment]
@bhancock8, @brahmaneya, requesting a review for this PR

**Comment by anerirana** [comment]
> @bhancock8, @brahmaneya, requesting a review for this PR

@paroma @fredsala

**Comment by bhancock8** [comment]
Thank you for this PR contribution, @anerirana! (And apologies for the delay—I was out of office this past week). Yes, I think adding a `progress_bar` parameter is an excellent idea, to provide an escape hatch for situations where it may become too verbose to be helpful or otherwise interfere with the output of script-based usage. After that, this should be good to go. Just re-ping (re-request review) from me when that's done and I'll be happy to approve.

**Comment by anerirana** [comment]
@bhancock8, thanks for the review. Added the progress bar param as discussed.

**Review by bhancock8 — APPROVED** [review]
Excellent. Thanks for the edit and new unit test. Good to merge!

**Comment by anerirana** [comment]
> Excellent. Thanks for the edit and new unit test. Good to merge!

@bhancock8 I don't have write access to this repository, you will have to merge the PR.

**Pull request merged**
