### PR TITLE
Bumping numpy version for Mac M1 compat

### PR DESCRIPTION
**Pull request by rsmith49**
## Description of proposed changes

According to https://github.com/snorkel-team/snorkel/issues/1689, numpy versions lower than 1.21 are not supported by the new Mac M1 chips. Bumping the upper bound of numpy to accommodate this.

## Related issue(s)

Fixes https://github.com/snorkel-team/snorkel/issues/1689

## Checklist

Need help on these? Just ask!

* [x] I have read the **CONTRIBUTING** document.
* [ ] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.
* [x] I have run `tox -e complex` and/or `tox -e spark` if appropriate.
* [] All new and existing tests passed.

### CODE REVIEW

**Comment by zexuan-zhou** [comment]
@ajratner @henryre @stephenbach @bhancock8

**Comment by bhancock8** [comment]
Let's rebase now that #1696	is merged, then note on #1695 that this is now resolved.

**Comment by zexuan-zhou** [comment]
@rsmith49 I think merging this PR will help py37 and py38 CI builds

**Comment by rsmith49** [comment]
@zexuan-zhou thanks for all the dev effort here! Looks like we addressed the mypy issues - ready for a review @bhancock8

**Review by bhancock8 — APPROVED** [review]
Changes lgtm! And proof is in the pudding—no changes to logic, only dependencies and types, and mypy is now satisfied (with helpful docstrings explaining conversions along the way). Ship it!

**Comment by zexuan-zhou** [comment]
@bhancock8 @rsmith49 Will there be a version release for this or what version should I use to install the latest version. Thank you

**Pull request merged**
