### PR TITLE
Fixing test_convergence

### PR DESCRIPTION
**Pull request by melonwater211**
This PR is a followup to Issue #1654 (@bhancock8). We have changed `n_epochs` from 10 to 20. Please let us know if there is anything else that should be done with regards to `test_convergence`. Additionally, there are several other tests that demonstrate similar behavior. Please let us know if we should send the details about those tests. Thank you.

### CODE REVIEW

**Review by rsmith49 — CHANGES_REQUESTED** [review]
Hi @melonwater211! Thanks for taking the initiative to make the tests more robust.

We actually want to keep tests deterministic for better reproducibility, so please uncomment the lines where the seed is set.

That being said, increasing the number of epochs to 20 sounds great, and we greatly appreciate you taking the time to run those experiments to see which approach reduced non-deterministic flakiness the most. Feel free to increase epochs to reduce flakiness in other tests as well.

**Comment by melonwater211** [comment]
Hi @rsmith49. 

After additional testing, we have determined that the best course of action may be to keep `n_epochs` at 10, increase `lr` to 0022549816312896175, and increase the values of the assertions on lines 68 and 75 to 0.06 and 0.07, respectively. After these changes, `test_convergence` failed 0 times (out of 2000 runs). Of course, if you would prefer to keep the tests deterministic, we will push the stabilization adjustments without removing the seed-setting code. Please let us know if there is anything else that should be done to fix this test.

We would be happy to raise PRs for other tests with similar issues. Thank you.

**Comment by melonwater211** [comment]
Hi @rsmith49.

After running additional tests, we have determined that increasing `n_epochs` to 50 and `lr` to 0.002383698505238875 would better reduce flakiness. Additionally, we have kept the seed-setting code, as requested. Please let us know if anything else should be done to fix this test. We would be happy to raise PRs about other flaky tests. Thank you.

**Comment by melonwater211** [comment]
Hi @rsmith49. I would also like to mention that, with these new changes in place, the probability of failure when the seed-setting code is removed is ~0.08%. Please let us know if anything else should be done or if the PR is ready to merge. Thank you.

**Comment by rsmith49** [comment]
Hi @melonwater211 ! Sorry for the late reply. We recently went through some CI upgrades for the checks to become more streamlined. However, because of this, existing PRs such as this one have the old CI checks still attached. 

Would you mind rebasing to the new master branch and pushing this PR from there? You can accomplish that by

    git pull
    git rebase master
    git push --force

**Comment by rsmith49** [comment]
Closing this as #1715 has addressed the same changes

**Pull request closed without merging**
